dist: trusty
sudo: false
language: rust
rust:
  - stable
  - beta
  - nightly
env:
  global:
    - RUSTFLAGS="-C prefer-dynamic"
cache: cargo

notifications:
  webhooks:
    urls:
      - secure: "LWc5Ky7Kxg7dHZjZ2i5YWqsoRyhwuBhCK4/Ii4wkfyShfPcJJObJVmcf/dYadpXVwF7e3E34LAO4hawdXbsO6yJNR96GKXg
jMhKmcUjMNtFHAVZRrJ+p8YzXsFTP/Jlm/1JGGn3ip9w8zcXZddMlLdDZzajJwEke5tnRE3VnEoseYBwtkUQ9i8Havt050IiE3HIRZIU8Z
oF0ICUaonGgv8kL1PZeU3WUngzTJ3Du36s3RYj+Js+xyFzMiK6aA1ibhTYAbINq5PCSUV8FUx8hYPb8Dgf+NhQC1eGjmvBwci3l88ArO3I
AA0M8SWqn02P9AXEZY573Vz1ZVG23Jdb/qr/yyQL4GVKk0rIzdIrCryARSDbpnHMZPt+TqtcDOLfPGPpq11UNgbVr1Ih0v76iNWbnnq1vt
oKuOIIKxCegeZg/SoUdYm31OKKAHL075+LG0/yqZHj3Z4lB8jWxnStUMJNxjTlzX8W4XRKZH9vDz9YdnzbexzPm94iYVM0OY9DbM2Dg8+J
bFKjwji3kf+T+12E2t4KI1rRKZg46dHJwUEpZLD5ARNWm/g2S/SFF/9diB85wtLU3t6mrcotUrJwAwxo76dePvXSAhcSY1bJGD43e/EDDu
E+9PhBXY4OHc0etJdclePqV5ovV9LQ9MRks2doE78hAwkrRWdCYfHqPG8k="
      - secure: "Mvcip6FbzEBEl5o2EAB+RuRJsi6ZzlcssmjzHHdKyPhttz4UsgubhtWv9axpDKWJq+A0Y4/6BEhuseHZaBt9TO8JJTz41VEbg2xBktjN
+fEPjQL6KeQS++5qEWwtzWMjj/oOp32egS7vaBah4cC/MiCGIfGggRu61uIMp59K5ww7N13OwMxlSogR8JwFdznOrJ56He1hQVICBZQFRxw0ah77o8P
tqp+6zrCImGSmJqDtJ2T2t8cCncHN+fDMwO1jH2a3gvsuu4cluwV+WhHDzH2MFOFuuOv0ylYKGku/1o40u+sOdWCLNNJ71jmnZSpwweBB0OklgXIJSD
Rb0Y5UHX8XVgpEce+NeBFEo5mJNgwdKbs1DswgISGcsJvE/c2sJvUGqGn4rnF2S2PINfqJ23GApQz9maISTU3bOF3qNIFAERW0EzMsvumGrHGITps5t
jiaV0Tzeky6eoywb6qP3+qA3BIG3qZgD32WEYvaD2RLD89bPuBRhXaN9IVLVxOTmmsAo1V9u0I3RDnCccvVM+VS+YBfSzcY7kVY58aWVrMSHIYYM4Q/
4CSSpMRzG5yEehC8CfOy+cy85Orcq74p0wo14ejUWvq/jyvmV//YKoi0unr3oKfTktwUPtof6EtFCAYK5bbx+sRIr5xETBqMyf5Gs1joQcmIqNCPpBq
fmBA="
    on_success: change
    on_failure: always
    on_start: never
